### PR TITLE
Add some basic tests and set up wercker.yml and hooks

### PR DESCRIPTION
**Pull request by MadManMathew**
Currently there are no tests, repo needs to be set up properly with hooks (wercker and github) needs wercker.yml aswell

While writing tests, found some small bugs. Will re-tag 1.1.0

### CODE REVIEW

**Comment by MadManMathew** [comment]
@switters @RongxinZhang   review please? 
I added ./sock.js because I found a small bug in it previsouly and my test proved such, so I will try to pr it on axon.

**Comment by RongxinZhang** [comment]
@MadManMathew this looks good! :+1: 

screen shot 2015-06-15 at 2 04 50 pm

**Comment by RongxinZhang** [comment]
@MadManMathew you can also add the app to wercker. https://app.wercker.com/#applications/create as a Retsly app

**Comment by CMClay** [comment]
:+1:

**Pull request merged**
