### PR TITLE
Rebase axon to include latest fixes

### PR DESCRIPTION
**Pull request by EnFinlay**
## Team

- @slajax 
- @thalesfsp
- @CMClay 
- @RongxinZhang 
- @xer0x 

## Overview

The source `axon` implementation which was forked to make `microservice` has some fixes that may fix the issue with sockets not closing properly (https://github.com/tj/axon/commit/196131a88b8b4cd8284b4b2ff8a6552408d43db4).

## Tasks

- [ ] Task 1
- [ ] Task 2

## Deployment

- [ ] Review point 1
- [ ] Review point 2

## Release

These changes are ${major | minor | patch}

### CODE REVIEW

**Comment by EnFinlay** [comment]
@CMClay @MadManMathew Quick review?

**Comment by MadManMathew** [comment]
👍

**Comment by EnFinlay** [comment]
@Jkhwan Stand-in review for Colin?

**Comment by xer0x** [comment]
👍

**Pull request merged**
