### PR TITLE
Microservices hard restart while attempting proper error handling

### PR DESCRIPTION
**Pull request by EnFinlay**
## Team
Team Lead: @kregensberg 
Dev: @EnFinlay
Review: @Jkhwan @RongxinZhang 

## Overview
Adds more checks that objects, properties and functions are what we expect them to be.  Helps prevent hard restarts.

### CODE REVIEW

**Comment by EnFinlay** [comment]
@Jkhwan @RongxinZhang Review?

**Comment by EnFinlay** [comment]
@Jkhwan @MadManMathew Review?

**Comment by Jkhwan** [comment]
:+1:

**Comment by MadManMathew** [comment]
:+1: was service job null? because it doesn't appear to be possible, I could be wrong

**Comment by EnFinlay** [comment]
@MadManMathew service job was `null` if a process connected to the raw `tcp` server without going through the `microservice` framework.  This is what was happening the case where hooks were being pointed at `localhost` + `microservice` port.

**Comment by MadManMathew** [comment]
ahh, should we log a warning in that case?

**Comment by EnFinlay** [comment]
@MadManMathew Yeah, good call.  I'll add that in

**Pull request merged**
