### PR TITLE
Serialized errors need status property

### PR DESCRIPTION
**Pull request by switters**
#### Synopsis

lib/server.js::49 - during serialization, ```error.status``` needs to be included in sent obj. -- otherwise api interprets all errors as 500s.

##### Required Steps
- [x] Add status field to serialized obj at location cited above.

##### After merge
- [ ] Release Retsly/microservice#1.5.2

### CODE REVIEW

**Comment by switters** [comment]
@MadManMathew @RongxinZhang one-liner, quick review?

**Comment by thalesfsp** [comment]
:+1:

**Comment by MadManMathew** [comment]
:+1:

**Comment by switters** [comment]
:rocket:

**Comment by RongxinZhang** [comment]
:v:Good to go. tested

**Pull request merged**
