### PR TITLE
Fix Log Formatting

### PR DESCRIPTION
**Pull request by CalvinScott**
## Team

Team Lead: @thalesfsp 
Project Lead: @calvinscott
Deployment Review: @slajax 

### Overview

After recent logd improvements, some of the logging in microservices need to be updated to match the context requirements.

### CODE REVIEW

**Comment by CalvinScott** [comment]
@RongxinZhang @thalesfsp Please review, this fixes the 'no method 'err'' error seen in production. This will be associated with a version bump.

**Comment by RongxinZhang** [comment]
:v: Looks good. 
- Please test on all repos.

**Comment by CalvinScott** [comment]
@RongxinZhang Looks good on my end but maybe I could also get your eyes on it just to be sure.

**Comment by RongxinZhang** [comment]
@CalvinScott - tried it in api and it seems to work well.

**Comment by thalesfsp** [comment]
@RongxinZhang [this](https://github.com/Retsly/microservice/blob/cf0e1554c5c297f9857456907888959beb6b441d/lib/client.js#L15) is correct? This is the way we instantiate a new log now? Should not be this:

```
this.logger = log(name, 'client');
```

**Comment by thalesfsp** [comment]
:+1: Good to go.

**Pull request merged**
